package com.example.appsaudebackend.Usuarios.Service;
import com.example.appsaudebackend.Modules.Auth.Model.UsuarioAuth;import com.example.appsaudebackend.Modules.Auth.Repository.UsuarioAuthRepository;import com.example.appsaudebackend.Modules.Usuarios.Dto.Request.*;import com.example.appsaudebackend.Modules.Usuarios.Persistencia.*;import com.example.appsaudebackend.Modules.Usuarios.Service.PerfilService;import com.example.appsaudebackend.Shared.Exception.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.security.crypto.password.PasswordEncoder;import java.util.Optional;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class PerfilServiceTest{@Mock UsuarioRepository userRepo;@Mock UsuarioAuthRepository authRepo;@Mock PasswordEncoder encoder;@InjectMocks PerfilService service;
@Test void obtencaoRetornaPerfil(){var u=new UsuarioModel();u.setNome("Ana");u.setEmail("a@x.com");u.setTelefone("1");when(userRepo.findByUsuarioAuthCpf("1")).thenReturn(Optional.of(u));assertEquals("Ana",service.obter("1").nome());}
@Test void atualizaPerfil(){var u=new UsuarioModel();u.setId(1L);when(userRepo.findByUsuarioAuthCpf("1")).thenReturn(Optional.of(u));when(userRepo.findByEmail("b@x.com")).thenReturn(Optional.empty());when(userRepo.save(u)).thenReturn(u);var r=service.atualizar("1",new AtualizarPerfilRequestDto("B","b@x.com","2"));assertEquals("B",r.nome());assertEquals("2",u.getTelefone());}
@Test void impedeEmailDeOutroUsuario(){var u=new UsuarioModel();u.setId(1L);var other=new UsuarioModel();other.setId(2L);when(userRepo.findByUsuarioAuthCpf("1")).thenReturn(Optional.of(u));when(userRepo.findByEmail("b@x.com")).thenReturn(Optional.of(other));assertThrows(ConflitoException.class,()->service.atualizar("1",new AtualizarPerfilRequestDto("B","b@x.com","2")));verify(userRepo,never()).save(any());}
@Test void alteraSenhaDepoisDeValidarSenhaAtual(){var a=new UsuarioAuth();a.setSenha("old");when(authRepo.findByCpf("1")).thenReturn(Optional.of(a));when(encoder.matches("oldRaw","old")).thenReturn(true);when(encoder.matches("newRaw","old")).thenReturn(false);when(encoder.encode("newRaw")).thenReturn("newHash");service.alterarSenha("1",new AlterarSenhaRequestDto("oldRaw","newRaw"));assertEquals("newHash",a.getSenha());verify(authRepo).save(a);}
@Test void senhaAtualErradaNaoSalva(){var a=new UsuarioAuth();a.setSenha("old");when(authRepo.findByCpf("1")).thenReturn(Optional.of(a));when(encoder.matches("x","old")).thenReturn(false);assertThrows(RegraNegocioException.class,()->service.alterarSenha("1",new AlterarSenhaRequestDto("x","y")));verify(authRepo,never()).save(any());}
}
